package fcopy;

import java.awt.Dimension;
import java.awt.Rectangle;
import java.io.File;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import utility.koneksi_database;

/**
 * @author Putra Prasetya
 */
public class laporan extends javax.swing.JFrame {
    private Connection conn = new koneksi_database().connect();
    private int id_admin;
    public laporan() {
        initComponents();
        setMinimumSize(new Dimension(850,540));
        rb_tampil_semua.setSelected(true);
        Locale locale = new Locale ("id","ID");
        Locale.setDefault(locale);
    }
    
    public laporan(Rectangle bound, int id) {
        initComponents();
        setMinimumSize(new Dimension(850,540));
        this.setBounds(bound);
        this.id_admin = id;
        
        // terima ukuran window & tetapkan di window yang aktif
        this.setBounds(bound);
               
        //saat restore dari kondisi maximize kembali ke ukuran minimal
        Dimension size = this.getSize();
        Double width = size.getWidth();
        Double height = size.getHeight();
        if (width > 1381 && height > 743) {
            this.setSize(850,540);
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rb_group_tampil = new javax.swing.ButtonGroup();
        bg21 = new utility.bg2();
        header_menu = new javax.swing.JPanel();
        menu_pegawai = new javax.swing.JButton();
        menu_supplier = new javax.swing.JButton();
        menu_pembelian = new javax.swing.JButton();
        menu_barang = new javax.swing.JButton();
        menu_penjualan = new javax.swing.JButton();
        menu_penyesuaian = new javax.swing.JButton();
        menu_laporan = new javax.swing.JButton();
        menu_stok = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        btn_pegawai = new javax.swing.JButton();
        btn_supplier = new javax.swing.JButton();
        btn_pembelian = new javax.swing.JButton();
        btn_stok = new javax.swing.JButton();
        dt_dari_pembelian = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dt_sampai_pembelian = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        dt_dari_stok = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        dt_sampai_stok = new com.toedter.calendar.JDateChooser();
        jLabel45 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        dt_dari_penjualan = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        dt_sampai_penjualan = new com.toedter.calendar.JDateChooser();
        btn_penjualan = new javax.swing.JButton();
        dt_dari_penyesuaian = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        dt_sampai_penyesuaian = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        btn_penyesuaian = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        rb_tampil_semua = new javax.swing.JRadioButton();
        rb_tampil_belum = new javax.swing.JRadioButton();
        rb_tampil_beres = new javax.swing.JRadioButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        dt_dari_pembelian_detail = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        dt_sampai_pembelian_detail = new com.toedter.calendar.JDateChooser();
        btn_pembelian_detail = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        dt_dari_penjualan_detail = new com.toedter.calendar.JDateChooser();
        jLabel15 = new javax.swing.JLabel();
        dt_sampai_penjualan_detail = new com.toedter.calendar.JDateChooser();
        btn_penjualan_detail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 450));

        header_menu.setBackground(new java.awt.Color(255, 255, 204, 150));

        menu_pegawai.setBackground(new java.awt.Color(255, 153, 51));
        menu_pegawai.setText("Pegawai");
        menu_pegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pegawaiActionPerformed(evt);
            }
        });

        menu_supplier.setBackground(new java.awt.Color(255, 153, 51));
        menu_supplier.setText("Supplier");
        menu_supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_supplierActionPerformed(evt);
            }
        });

        menu_pembelian.setBackground(new java.awt.Color(255, 153, 51));
        menu_pembelian.setText("Pembelian");
        menu_pembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pembelianActionPerformed(evt);
            }
        });

        menu_barang.setBackground(new java.awt.Color(255, 153, 51));
        menu_barang.setText("Barang");
        menu_barang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_barangActionPerformed(evt);
            }
        });

        menu_penjualan.setBackground(new java.awt.Color(255, 153, 51));
        menu_penjualan.setText("Penjualan");
        menu_penjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_penjualanActionPerformed(evt);
            }
        });

        menu_penyesuaian.setBackground(new java.awt.Color(255, 153, 51));
        menu_penyesuaian.setText("Penyesuaian");
        menu_penyesuaian.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_penyesuaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_penyesuaianActionPerformed(evt);
            }
        });

        menu_laporan.setBackground(new java.awt.Color(255, 153, 51));
        menu_laporan.setForeground(new java.awt.Color(255, 255, 255));
        menu_laporan.setText("Laporan");
        menu_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_laporanActionPerformed(evt);
            }
        });

        menu_stok.setBackground(new java.awt.Color(255, 153, 51));
        menu_stok.setText("Stok");
        menu_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_stokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout header_menuLayout = new javax.swing.GroupLayout(header_menu);
        header_menu.setLayout(header_menuLayout);
        header_menuLayout.setHorizontalGroup(
            header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu_pegawai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_supplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_barang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_pembelian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_penjualan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_penyesuaian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_laporan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        header_menuLayout.setVerticalGroup(
            header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(menu_pegawai)
                .addComponent(menu_supplier)
                .addComponent(menu_pembelian)
                .addComponent(menu_barang)
                .addComponent(menu_penjualan)
                .addComponent(menu_penyesuaian)
                .addComponent(menu_laporan)
                .addComponent(menu_stok))
        );

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel38.setText("Laporan Pegawai-------------");

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel39.setText("Laporan Supplier-------------");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel42.setText("Laporan Pembelian----------");

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel43.setText("Laporan Stok------------------");

        btn_pegawai.setText("Cetak");
        btn_pegawai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pegawaiActionPerformed(evt);
            }
        });

        btn_supplier.setText("Cetak");
        btn_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_supplierActionPerformed(evt);
            }
        });

        btn_pembelian.setText("Cetak");
        btn_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembelianActionPerformed(evt);
            }
        });

        btn_stok.setText("Cetak");
        btn_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_stokActionPerformed(evt);
            }
        });

        dt_dari_pembelian.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel3.setText("Dari :");

        jLabel4.setText(" Sampai :");

        jLabel5.setText("Dari :");

        dt_dari_stok.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel6.setText(" Sampai :");

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel45.setText("Laporan Penjualan-----------");

        jLabel10.setText("Dari :");

        dt_dari_penjualan.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel11.setText(" Sampai :");

        btn_penjualan.setText("Cetak");
        btn_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualanActionPerformed(evt);
            }
        });

        dt_dari_penyesuaian.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel12.setText("Dari :");

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel46.setText("Laporan Penyesuaian-------");

        jLabel13.setText(" Sampai :");

        btn_penyesuaian.setText("Cetak");
        btn_penyesuaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penyesuaianActionPerformed(evt);
            }
        });

        jLabel1.setText("Tampilkan :");

        rb_group_tampil.add(rb_tampil_semua);
        rb_tampil_semua.setText("Semua");

        rb_group_tampil.add(rb_tampil_belum);
        rb_tampil_belum.setText("Belum Sesuai");

        rb_group_tampil.add(rb_tampil_beres);
        rb_tampil_beres.setText("Beres");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel44.setText("Laporan Pembelian Detail--");

        jLabel7.setText("Dari :");

        dt_dari_pembelian_detail.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel8.setText(" Sampai :");

        btn_pembelian_detail.setText("Cetak");
        btn_pembelian_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembelian_detailActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel47.setText("Laporan Penjualan Detail---");

        jLabel14.setText("Dari :");

        dt_dari_penjualan_detail.setPreferredSize(new java.awt.Dimension(105, 20));

        jLabel15.setText(" Sampai :");

        btn_penjualan_detail.setText("Cetak");
        btn_penjualan_detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_penjualan_detailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg21Layout = new javax.swing.GroupLayout(bg21);
        bg21.setLayout(bg21Layout);
        bg21Layout.setHorizontalGroup(
            bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(bg21Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_tampil_semua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_tampil_belum)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb_tampil_beres)
                        .addGap(18, 18, 18)
                        .addComponent(btn_penyesuaian, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dt_dari_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dt_sampai_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel39, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel46, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel47, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bg21Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dt_dari_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dt_sampai_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btn_pegawai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_supplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(bg21Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dt_dari_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dt_sampai_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bg21Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dt_dari_penyesuaian, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dt_sampai_penyesuaian, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90))
                            .addGroup(bg21Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dt_dari_penjualan_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dt_sampai_penjualan_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_penjualan_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dt_dari_pembelian_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dt_sampai_pembelian_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pembelian_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        bg21Layout.setVerticalGroup(
            bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg21Layout.createSequentialGroup()
                .addComponent(header_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_pegawai))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_supplier))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel42, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_pembelian))
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dt_dari_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_sampai_pembelian, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_pembelian_detail))
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dt_dari_pembelian_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_sampai_pembelian_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel43, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_stok))
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dt_dari_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_sampai_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_penjualan))
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dt_dari_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_sampai_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btn_penjualan_detail))
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dt_dari_penjualan_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_sampai_penjualan_detail, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(dt_dari_penyesuaian, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_sampai_penyesuaian, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rb_tampil_semua)
                    .addComponent(rb_tampil_belum)
                    .addComponent(rb_tampil_beres)
                    .addComponent(btn_penyesuaian))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pegawaiActionPerformed
        Rectangle laporanBound = this.getBounds();
        new pegawai(laporanBound, id_admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_pegawaiActionPerformed

    private void menu_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_supplierActionPerformed
        Rectangle laporanBound = this.getBounds();
        new supplier(laporanBound, id_admin).setVisible(true);
        this.dispose();       
    }//GEN-LAST:event_menu_supplierActionPerformed

    private void menu_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pembelianActionPerformed
        Rectangle laporanBound = this.getBounds();
        new pembelian(laporanBound, id_admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_pembelianActionPerformed

    private void menu_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_barangActionPerformed
        Rectangle laporanBound = this.getBounds();
        new barang(laporanBound, id_admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_barangActionPerformed

    private void menu_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_penjualanActionPerformed
        Rectangle laporanBound = this.getBounds();
        new penjualan(laporanBound, id_admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_penjualanActionPerformed

    private void menu_penyesuaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_penyesuaianActionPerformed
        Rectangle laporanBound = this.getBounds();
        new penyesuaian(laporanBound, id_admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_penyesuaianActionPerformed

    private void menu_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_laporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menu_laporanActionPerformed

    private void btn_pegawaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pegawaiActionPerformed
        try{
            String namaFile = "src/ireport/pegawai.jasper";
            Connection conn = new koneksi_database().connect();
            
            //GetData
            HashMap parameter = new HashMap();
            File report_file = new File (namaFile);
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
            JasperViewer.viewReport(jasperPrint, false); 
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (JRException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btn_pegawaiActionPerformed

    private void menu_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_stokActionPerformed
        Rectangle laporanBound = this.getBounds();
        new stok(laporanBound, id_admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_stokActionPerformed

    private void btn_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_supplierActionPerformed
        try{
            String namaFile = "src/ireport/supplier.jasper";
            Connection conn = new koneksi_database().connect();
            HashMap parameter = new HashMap();
            File report_file = new File (namaFile);
            
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
            JasperViewer.viewReport(jasperPrint, false); 
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (JRException e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
    }//GEN-LAST:event_btn_supplierActionPerformed

    private void btn_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembelianActionPerformed
        Date dari_pembelian = (Date) dt_dari_pembelian.getDate();
        Date sampai_pembelian = (Date) dt_sampai_pembelian.getDate();
        
        if(dari_pembelian==null){
            JOptionPane.showMessageDialog(null, "Pembelian 'Dari' Tanggal Belum Diisi !");
        } else if (sampai_pembelian==null){
            JOptionPane.showMessageDialog(null, "Pembelian 'Sampai' Tanggal Belum Diisi !");
        } else {
            SimpleDateFormat Format_English = new SimpleDateFormat("yyyy-MM-dd");            
            String dari_english = Format_English.format(dari_pembelian);        
            String sampai_english = Format_English.format(sampai_pembelian);
            
            SimpleDateFormat Format_Indo = new SimpleDateFormat("dd-MM-yyyy");
            String dari_indo = Format_Indo.format(dari_pembelian);        
            String sampai_indo = Format_Indo.format(sampai_pembelian);
            
            try{
                String namaFile = "src/ireport/pembelian.jasper";
                
                Map<String, Object> parameter = new HashMap<String, Object>();
                parameter.put("PARA_DARI_INDO", dari_indo);
                parameter.put("PARA_SAMPAI_INDO", sampai_indo);
                parameter.put("PARA_DARI_ENGLISH", dari_english);
                parameter.put("PARA_SAMPAI_ENGLISH", sampai_english);
                File report_file = new File (namaFile);
            
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
                JasperViewer.viewReport(jasperPrint, false); 
                JasperViewer.setDefaultLookAndFeelDecorated(true);

            } catch (JRException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }            
        }
    }//GEN-LAST:event_btn_pembelianActionPerformed

    private void btn_pembelian_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembelian_detailActionPerformed
        Date dari_pembelian = (Date) dt_dari_pembelian_detail.getDate();
        Date sampai_pembelian = (Date) dt_sampai_pembelian_detail.getDate();
        
        if(dari_pembelian==null){
            JOptionPane.showMessageDialog(null, "Pembelian Detail 'Dari' Tanggal Belum Diisi !");
        } else if (sampai_pembelian==null){
            JOptionPane.showMessageDialog(null, "Pembelian Detail 'Sampai' Tanggal Belum Diisi !");
        } else {
            SimpleDateFormat Format_English = new SimpleDateFormat("yyyy-MM-dd");            
            String dari_english = Format_English.format(dari_pembelian);        
            String sampai_english = Format_English.format(sampai_pembelian);
            
            SimpleDateFormat Format_Indo = new SimpleDateFormat("dd-MM-yyyy");
            String dari_indo = Format_Indo.format(dari_pembelian);        
            String sampai_indo = Format_Indo.format(sampai_pembelian);
            
            try{
                String namaFile = "src/ireport/pembelian_detail.jasper";
                
                Map<String, Object> parameter = new HashMap<String, Object>();
                parameter.put("PARA_DARI_INDO", dari_indo);
                parameter.put("PARA_SAMPAI_INDO", sampai_indo);
                parameter.put("PARA_DARI_ENGLISH", dari_english);
                parameter.put("PARA_SAMPAI_ENGLISH", sampai_english);
                File report_file = new File (namaFile);
            
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
                JasperViewer.viewReport(jasperPrint, false); 
                JasperViewer.setDefaultLookAndFeelDecorated(true);

            } catch (JRException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }            
        }
    }//GEN-LAST:event_btn_pembelian_detailActionPerformed

    private void btn_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_stokActionPerformed
        Date dari_pembelian = (Date) dt_dari_stok.getDate();
        Date sampai_pembelian = (Date) dt_sampai_stok.getDate();
        
        if(dari_pembelian==null){
            JOptionPane.showMessageDialog(null, "Stok 'Dari' Tanggal Belum Diisi !");
        } else if (sampai_pembelian==null){
            JOptionPane.showMessageDialog(null, "Stok 'Sampai' Tanggal Belum Diisi !");
        } else {
            SimpleDateFormat Format_English = new SimpleDateFormat("yyyy-MM-dd");            
            String dari_english = Format_English.format(dari_pembelian);        
            String sampai_english = Format_English.format(sampai_pembelian);
            
            SimpleDateFormat Format_Indo = new SimpleDateFormat("dd-MM-yyyy");
            String dari_indo = Format_Indo.format(dari_pembelian);        
            String sampai_indo = Format_Indo.format(sampai_pembelian);
            
            try{
                String namaFile = "src/ireport/stok.jasper";
                
                Map<String, Object> parameter = new HashMap<String, Object>();
                parameter.put("PARA_DARI_INDO", dari_indo);
                parameter.put("PARA_SAMPAI_INDO", sampai_indo);
                parameter.put("PARA_DARI_ENGLISH", dari_english);
                parameter.put("PARA_SAMPAI_ENGLISH", sampai_english);
                File report_file = new File (namaFile);
            
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
                JasperViewer.viewReport(jasperPrint, false); 
                JasperViewer.setDefaultLookAndFeelDecorated(true);

            } catch (JRException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }            
        }
    }//GEN-LAST:event_btn_stokActionPerformed

    private void btn_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualanActionPerformed
        Date dari_pembelian = (Date) dt_dari_penjualan.getDate();
        Date sampai_pembelian = (Date) dt_sampai_penjualan.getDate();
        
        if(dari_pembelian==null){
            JOptionPane.showMessageDialog(null, "Penjualan 'Dari' Tanggal Belum Diisi !");
        } else if (sampai_pembelian==null){
            JOptionPane.showMessageDialog(null, "Penjualan 'Sampai' Tanggal Belum Diisi !");
        } else {
            SimpleDateFormat Format_English = new SimpleDateFormat("yyyy-MM-dd");            
            String dari_english = Format_English.format(dari_pembelian);        
            String sampai_english = Format_English.format(sampai_pembelian);
            
            SimpleDateFormat Format_Indo = new SimpleDateFormat("dd-MM-yyyy");
            String dari_indo = Format_Indo.format(dari_pembelian);        
            String sampai_indo = Format_Indo.format(sampai_pembelian);
            
            try{
                String namaFile = "src/ireport/penjualan.jasper";
                
                Map<String, Object> parameter = new HashMap<String, Object>();
                parameter.put("PARA_DARI_INDO", dari_indo);
                parameter.put("PARA_SAMPAI_INDO", sampai_indo);
                parameter.put("PARA_DARI_ENGLISH", dari_english);
                parameter.put("PARA_SAMPAI_ENGLISH", sampai_english);
                File report_file = new File (namaFile);
            
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
                JasperViewer.viewReport(jasperPrint, false); 
                JasperViewer.setDefaultLookAndFeelDecorated(true);

            } catch (JRException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }            
        }
    }//GEN-LAST:event_btn_penjualanActionPerformed

    private void btn_penjualan_detailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penjualan_detailActionPerformed
        Date dari_pembelian = (Date) dt_dari_penjualan_detail.getDate();
        Date sampai_pembelian = (Date) dt_sampai_penjualan_detail.getDate();
        
        if(dari_pembelian==null){
            JOptionPane.showMessageDialog(null, "Penjualan Detail 'Dari' Tanggal Belum Diisi !");
        } else if (sampai_pembelian==null){
            JOptionPane.showMessageDialog(null, "Penjualan Detail 'Sampai' Tanggal Belum Diisi !");
        } else {
            SimpleDateFormat Format_English = new SimpleDateFormat("yyyy-MM-dd");            
            String dari_english = Format_English.format(dari_pembelian);        
            String sampai_english = Format_English.format(sampai_pembelian);
            
            SimpleDateFormat Format_Indo = new SimpleDateFormat("dd-MM-yyyy");
            String dari_indo = Format_Indo.format(dari_pembelian);        
            String sampai_indo = Format_Indo.format(sampai_pembelian);
            
            try{
                String namaFile = "src/ireport/penjualan_detail.jasper";
                
                Map<String, Object> parameter = new HashMap<String, Object>();
                parameter.put("PARA_DARI_INDO", dari_indo);
                parameter.put("PARA_SAMPAI_INDO", sampai_indo);
                parameter.put("PARA_DARI_ENGLISH", dari_english);
                parameter.put("PARA_SAMPAI_ENGLISH", sampai_english);
                File report_file = new File (namaFile);
            
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
                JasperViewer.viewReport(jasperPrint, false); 
                JasperViewer.setDefaultLookAndFeelDecorated(true);

            } catch (JRException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }            
        }
    }//GEN-LAST:event_btn_penjualan_detailActionPerformed

    private void btn_penyesuaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_penyesuaianActionPerformed
        String status="", status2="";        
        if(rb_tampil_belum.isSelected()) status = "Belum Sesuai";
        else if (rb_tampil_beres.isSelected()) status = "Beres";
        else {
            status = "Belum Sesuai";
            status2 = "Beres";
        }
        
        Date dari_penyesuaian = (Date) dt_dari_penyesuaian.getDate();
        Date sampai_penyesuaian = (Date) dt_sampai_penyesuaian.getDate();
        
        if(dari_penyesuaian==null){
            JOptionPane.showMessageDialog(null, "Penyesuaian 'Dari' Tanggal Belum Diisi !");
        } else if (sampai_penyesuaian==null){
            JOptionPane.showMessageDialog(null, "Penyesuaian 'Sampai' Tanggal Belum Diisi !");
        } else {
            SimpleDateFormat Format_English = new SimpleDateFormat("yyyy-MM-dd");            
            String dari_english = Format_English.format(dari_penyesuaian);        
            String sampai_english = Format_English.format(sampai_penyesuaian);
            
            SimpleDateFormat Format_Indo = new SimpleDateFormat("dd-MM-yyyy");
            String dari_indo = Format_Indo.format(dari_penyesuaian);        
            String sampai_indo = Format_Indo.format(sampai_penyesuaian);
            
            try{
                String namaFile = "src/ireport/penyesuaian.jasper";
                
                Map<String, Object> parameter = new HashMap<String, Object>();
                parameter.put("PARA_DARI_INDO", dari_indo);
                parameter.put("PARA_SAMPAI_INDO", sampai_indo);
                parameter.put("PARA_DARI_ENGLISH", dari_english);
                parameter.put("PARA_SAMPAI_ENGLISH", sampai_english);
                parameter.put("PARA_STATUS",status);
                parameter.put("PARA_STATUS2", status2);
                File report_file = new File (namaFile);
            
                JasperReport jasperReport = (JasperReport) JRLoader.loadObject(report_file.getPath());
                JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport,parameter,conn);
                JasperViewer.viewReport(jasperPrint, false); 
                JasperViewer.setDefaultLookAndFeelDecorated(true);

            } catch (JRException e){
                JOptionPane.showMessageDialog(null,e.getMessage());
            }            
        }
    }//GEN-LAST:event_btn_penyesuaianActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
                

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private utility.bg2 bg21;
    private javax.swing.JButton btn_pegawai;
    private javax.swing.JButton btn_pembelian;
    private javax.swing.JButton btn_pembelian_detail;
    private javax.swing.JButton btn_penjualan;
    private javax.swing.JButton btn_penjualan_detail;
    private javax.swing.JButton btn_penyesuaian;
    private javax.swing.JButton btn_stok;
    private javax.swing.JButton btn_supplier;
    private com.toedter.calendar.JDateChooser dt_dari_pembelian;
    private com.toedter.calendar.JDateChooser dt_dari_pembelian_detail;
    private com.toedter.calendar.JDateChooser dt_dari_penjualan;
    private com.toedter.calendar.JDateChooser dt_dari_penjualan_detail;
    private com.toedter.calendar.JDateChooser dt_dari_penyesuaian;
    private com.toedter.calendar.JDateChooser dt_dari_stok;
    private com.toedter.calendar.JDateChooser dt_sampai_pembelian;
    private com.toedter.calendar.JDateChooser dt_sampai_pembelian_detail;
    private com.toedter.calendar.JDateChooser dt_sampai_penjualan;
    private com.toedter.calendar.JDateChooser dt_sampai_penjualan_detail;
    private com.toedter.calendar.JDateChooser dt_sampai_penyesuaian;
    private com.toedter.calendar.JDateChooser dt_sampai_stok;
    private javax.swing.JPanel header_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton menu_barang;
    private javax.swing.JButton menu_laporan;
    private javax.swing.JButton menu_pegawai;
    private javax.swing.JButton menu_pembelian;
    private javax.swing.JButton menu_penjualan;
    private javax.swing.JButton menu_penyesuaian;
    private javax.swing.JButton menu_stok;
    private javax.swing.JButton menu_supplier;
    private javax.swing.ButtonGroup rb_group_tampil;
    private javax.swing.JRadioButton rb_tampil_belum;
    private javax.swing.JRadioButton rb_tampil_beres;
    private javax.swing.JRadioButton rb_tampil_semua;
    // End of variables declaration//GEN-END:variables
}
