package fcopy;

import java.awt.Dimension;
import java.awt.Rectangle;
import javax.swing.JFrame;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import utility.koneksi_database;

// @author Putra Prasetya
public class pegawai extends javax.swing.JFrame {
    private Connection conn = new koneksi_database().connect();
    private DefaultTableModel tabmode;
    private int id_admin;
    private String name;
    
    public pegawai() {
        initComponents();
        tabelPegawai();
        rb_pria.setSelected(true);
        ta_alamat.setLineWrap(true);
        ta_alamat.setWrapStyleWord(true);
        setMinimumSize(new Dimension(850,540));
    }
    
    public pegawai(Rectangle bound, int id) {
        initComponents();
        tabelPegawai();
        rb_pria.setSelected(true);
        setMinimumSize(new Dimension(850,540));
        this.id_admin = id;
        
        // terima ukuran window & tetapkan di window yang aktif
        this.setBounds(bound);
               
        //saat restore dari kondisi maximize kembali ke ukuran minimal
        Dimension size = this.getSize();
        Double width = size.getWidth();
        Double height = size.getHeight();
        if (width > 1381 && height > 743) {
            this.setSize(850,540);
            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        }
    }
    
    public pegawai(int id) {
        initComponents();
        this.id_admin = id;
        tabelPegawai();
        rb_pria.setSelected(true);
        ta_alamat.setLineWrap(true);
        ta_alamat.setWrapStyleWord(true);
        setMinimumSize(new Dimension(850,540));
    }
    
    protected void clear(){
        tf_nama.setText("");
        tf_tmpt_lahir.setText("");
        date_tgl_lahir.setDate(null);
        rb_pria.setSelected(true);
        ta_alamat.setText("");
        tf_no_telp.setText("");
        tf_nama.requestFocus();      
    }

    protected void tabelPegawai() {
        Object[] Baris = {"Nama", "No. Telepon", "Alamat"};
        tabmode = new DefaultTableModel(null, Baris);
        tbl_pegawai.setModel(tabmode);
        String sql = "SELECT nama_peg, telp_peg, alamat_peg FROM pegawai";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){                
                String a = hasil.getString("nama_peg");                
                String b = hasil.getString("telp_peg");
                String c = hasil.getString("alamat_peg");                
                
                String[] data={a,b,c};
                tabmode.addRow(data);
            }
            
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Tabel tidak bisa ditampilkan"+e);
        }
    }
    
    protected boolean cekNama(String nama){
        boolean z = false;
        nama = tf_nama.getText();
        String sql = "SELECT nama_peg FROM pegawai WHERE nama_peg = '"+nama+"'";
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            String a = "";
            while(hasil.next()){
                a = hasil.getString("nama_peg");
            }
            if(a.equals(nama)) {                
                z = true;
            }            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal ambil nama : "+e);
        }
        return z;
    }
    
    protected int getId(){
        int id = 0;
        String sql = "SELECT id_peg FROM pegawai WHERE nama_peg = '"+name+"'";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while(hasil.next()){
                id = hasil.getInt("id_peg");
            }            
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, "Gagal ambil id : "+e);
        }
        return id;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bg21 = new utility.bg2();
        header_menu = new javax.swing.JPanel();
        menu_pegawai = new javax.swing.JButton();
        menu_supplier = new javax.swing.JButton();
        menu_pembelian = new javax.swing.JButton();
        menu_barang = new javax.swing.JButton();
        menu_penjualan = new javax.swing.JButton();
        menu_penyesuaian = new javax.swing.JButton();
        menu_laporan = new javax.swing.JButton();
        menu_stok = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf_nama = new javax.swing.JTextField();
        tf_tmpt_lahir = new javax.swing.JTextField();
        rb_pria = new javax.swing.JRadioButton();
        rb_wanita = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        tf_no_telp = new javax.swing.JTextField();
        btn_simpan = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        btn_bersihkan = new javax.swing.JButton();
        tabelScrollPane = new javax.swing.JScrollPane();
        tbl_pegawai = new javax.swing.JTable();
        alamatScrollPane = new javax.swing.JScrollPane();
        ta_alamat = new javax.swing.JTextArea();
        date_tgl_lahir = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 450));

        header_menu.setBackground(new java.awt.Color(255, 255, 204, 150));

        menu_pegawai.setBackground(new java.awt.Color(255, 153, 51));
        menu_pegawai.setForeground(new java.awt.Color(255, 255, 255));
        menu_pegawai.setText("Pegawai");
        menu_pegawai.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        menu_supplier.setBackground(new java.awt.Color(255, 153, 51));
        menu_supplier.setText("Supplier");
        menu_supplier.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_supplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_supplierActionPerformed(evt);
            }
        });

        menu_pembelian.setBackground(new java.awt.Color(255, 153, 51));
        menu_pembelian.setText("Pembelian");
        menu_pembelian.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_pembelianActionPerformed(evt);
            }
        });

        menu_barang.setBackground(new java.awt.Color(255, 153, 51));
        menu_barang.setText("Barang");
        menu_barang.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_barang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_barangActionPerformed(evt);
            }
        });

        menu_penjualan.setBackground(new java.awt.Color(255, 153, 51));
        menu_penjualan.setText("Penjualan");
        menu_penjualan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_penjualanActionPerformed(evt);
            }
        });

        menu_penyesuaian.setBackground(new java.awt.Color(255, 153, 51));
        menu_penyesuaian.setText("Penyesuaian");
        menu_penyesuaian.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_penyesuaian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_penyesuaianActionPerformed(evt);
            }
        });

        menu_laporan.setBackground(new java.awt.Color(255, 153, 51));
        menu_laporan.setText("Laporan");
        menu_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menu_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_laporanActionPerformed(evt);
            }
        });

        menu_stok.setBackground(new java.awt.Color(255, 153, 51));
        menu_stok.setText("Stok");
        menu_stok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu_stokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout header_menuLayout = new javax.swing.GroupLayout(header_menu);
        header_menu.setLayout(header_menuLayout);
        header_menuLayout.setHorizontalGroup(
            header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_menuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menu_pegawai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_supplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_barang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_pembelian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_stok, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_penjualan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_penyesuaian)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu_laporan)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        header_menuLayout.setVerticalGroup(
            header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(header_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(menu_pegawai)
                .addComponent(menu_supplier)
                .addComponent(menu_pembelian)
                .addComponent(menu_barang)
                .addComponent(menu_penjualan)
                .addComponent(menu_penyesuaian)
                .addComponent(menu_laporan)
                .addComponent(menu_stok))
        );

        jLabel1.setText("Nama");
        jLabel1.setMaximumSize(new java.awt.Dimension(500, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 14));

        jLabel2.setText("Tempat Lahir");
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(80, 14));

        jLabel3.setText("Tanggal Lahir");
        jLabel3.setMaximumSize(new java.awt.Dimension(500, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(50, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(80, 14));

        jLabel4.setText("Jenis Kelamin");
        jLabel4.setMaximumSize(new java.awt.Dimension(500, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(50, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(80, 14));

        jLabel5.setText("Alamat");
        jLabel5.setPreferredSize(new java.awt.Dimension(80, 14));

        buttonGroup1.add(rb_pria);
        rb_pria.setText("Pria");

        buttonGroup1.add(rb_wanita);
        rb_wanita.setText("Wanita");

        jLabel6.setText("No. Telepon");
        jLabel6.setPreferredSize(new java.awt.Dimension(80, 14));

        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        btn_bersihkan.setText("Bersihkan");
        btn_bersihkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bersihkanActionPerformed(evt);
            }
        });

        tbl_pegawai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "No.Telepon", "Alamat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_pegawai.getTableHeader().setReorderingAllowed(false);
        tbl_pegawai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_pegawaiMouseClicked(evt);
            }
        });
        tabelScrollPane.setViewportView(tbl_pegawai);
        if (tbl_pegawai.getColumnModel().getColumnCount() > 0) {
            tbl_pegawai.getColumnModel().getColumn(1).setPreferredWidth(10);
        }

        ta_alamat.setColumns(20);
        ta_alamat.setRows(5);
        alamatScrollPane.setViewportView(ta_alamat);

        javax.swing.GroupLayout bg21Layout = new javax.swing.GroupLayout(bg21);
        bg21.setLayout(bg21Layout);
        bg21Layout.setHorizontalGroup(
            bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(header_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg21Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tf_nama)
                    .addComponent(tf_tmpt_lahir)
                    .addComponent(alamatScrollPane)
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(rb_pria)
                        .addGap(18, 18, 18)
                        .addComponent(rb_wanita))
                    .addComponent(tf_no_telp)
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_bersihkan, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date_tgl_lahir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(tabelScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        bg21Layout.setVerticalGroup(
            bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg21Layout.createSequentialGroup()
                .addComponent(header_menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg21Layout.createSequentialGroup()
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_tmpt_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_tgl_lahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rb_pria)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rb_wanita))
                        .addGap(11, 11, 11)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(alamatScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tf_no_telp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_simpan)
                            .addComponent(btn_ubah))
                        .addGap(13, 13, 13)
                        .addGroup(bg21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_bersihkan)
                            .addComponent(btn_hapus))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addComponent(tabelScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menu_supplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_supplierActionPerformed
        Rectangle pegawaiBound = this.getBounds();
        new supplier(pegawaiBound, id_admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_supplierActionPerformed

    private void menu_pembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_pembelianActionPerformed
        Rectangle pegawaiBound = this.getBounds();
        new pembelian(pegawaiBound, id_admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_pembelianActionPerformed

    private void menu_barangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_barangActionPerformed
        Rectangle pegawaiBound = this.getBounds();
        new barang(pegawaiBound, id_admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_barangActionPerformed

    private void menu_penjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_penjualanActionPerformed
        Rectangle pegawaiBound = this.getBounds();
        new penjualan(pegawaiBound, id_admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_penjualanActionPerformed

    private void menu_penyesuaianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_penyesuaianActionPerformed
        Rectangle pegawaiBound = this.getBounds();
        new penyesuaian(pegawaiBound, id_admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_penyesuaianActionPerformed

    private void menu_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_laporanActionPerformed
        Rectangle pegawaiBound = this.getBounds();
        new laporan(pegawaiBound, id_admin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menu_laporanActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String nama = tf_nama.getText();
        if (nama.equals("")){
            JOptionPane.showMessageDialog(null, 
                "Nama kosong !. Silahkan isi terlebih dahulu");
            return;
        } else if (cekNama(nama)){
            JOptionPane.showMessageDialog(null, 
                "Nama sudah ada !. Silahkan tulis nama lain");
            return;
        }
        String sql = "INSERT INTO pegawai VALUES (?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, null);
            stat.setString(2, nama);
            stat.setString(3, tf_tmpt_lahir.getText());
            
            Date cast_tgl = (Date) date_tgl_lahir.getDate();
            SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd"); 
            String strDate = Date_Format.format(cast_tgl);
            stat.setString(4, strDate);       
            
            String jkel="";
            if(rb_pria.isSelected()) jkel="Pria";
            else jkel="Wanita";            
            stat.setString(5, jkel);
            stat.setString(6, ta_alamat.getText());
            stat.setString(7, tf_no_telp.getText());
            
            stat.executeUpdate();
            clear();            
            tabelPegawai();
            
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null, "Data tidak bisa dimasukkan"+e);
        }        
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed
        int id = getId();
        String nama = tf_nama.getText();        
        if (nama.equals("")){
            JOptionPane.showMessageDialog(null, 
                "Nama kosong !. Silahkan isi terlebih dahulu");
            return;
        }
        try {
            String sql = "UPDATE pegawai SET "
                        + "nama_peg=?,"
                        + "tmpt_lahir_peg=?,"
                        + "tgl_lahir_peg=?,"
                        + "jns_kel_peg=?,"
                        + "alamat_peg=?,"
                        + "telp_peg=? "
                       + "WHERE id_peg=?";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, nama);
            stat.setString(2, tf_tmpt_lahir.getText());
            Date cast_tgl = (Date) date_tgl_lahir.getDate();
            SimpleDateFormat Date_Format = new SimpleDateFormat("yyyy-MM-dd"); 
            String strDate = Date_Format.format(cast_tgl);
            stat.setString(3, strDate);  
            
            String jkel="";
            if(rb_pria.isSelected()) jkel="Pria";
            else jkel="Wanita";
            stat.setString(4, jkel);
            stat.setString(5, ta_alamat.getText());
            stat.setString(6, tf_no_telp.getText());
            stat.setInt(7, id);
            
            stat.executeUpdate();
            clear();            
            tabelPegawai();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Data Gagal Diubah "+e);
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int id = getId();
        int ok = JOptionPane.showConfirmDialog(null,"hapus","Konfirmasi Dialog", 
                 JOptionPane.YES_NO_OPTION);
        if (ok==0){
            String sql = "DELETE FROM pegawai WHERE nama_peg='"+id+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                clear();                
                tabelPegawai();
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data gagal dihapus"+e);
            }
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void btn_bersihkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bersihkanActionPerformed
        clear();        
    }//GEN-LAST:event_btn_bersihkanActionPerformed

    private void tbl_pegawaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_pegawaiMouseClicked
        
        int bar = tbl_pegawai.getSelectedRow();
        String nama = tabmode.getValueAt(bar, 0).toString();
        this.name = nama;
        String sql = "SELECT nama_peg, tmpt_lahir_peg, tgl_lahir_peg, jns_kel_peg, alamat_peg, telp_peg FROM pegawai WHERE nama_peg = '"+nama+"'";
        
        try {
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);            
            String a = "", b = "", d = "", e = "", f = "", g = "";
            
            while(hasil.next()){
                a = hasil.getString("nama_peg");
                b = hasil.getString("tmpt_lahir_peg");
                Date c = hasil.getDate("tgl_lahir_peg");
                d = hasil.getString("jns_kel_peg");
                e = hasil.getString("alamat_peg");
                f = hasil.getString("telp_peg");
                date_tgl_lahir.setDate(c);                
            }
            tf_nama.setText(a);
            tf_tmpt_lahir.setText(b);
            switch (d) {
                case "Pria":
                    rb_pria.setSelected(true);
                    rb_wanita.setSelected(false);
                    break;
                case "Wanita":
                    rb_pria.setSelected(false);
                    rb_wanita.setSelected(true);
                    break;
                default:
                    rb_pria.setSelected(false);
                    rb_wanita.setSelected(false);
                    break;
            }
            ta_alamat.setText(e);
            tf_no_telp.setText(f);
        }catch(SQLException ee){
            JOptionPane.showMessageDialog(null, "Data gagal diambil"+ee);
        }
    }//GEN-LAST:event_tbl_pegawaiMouseClicked

    private void menu_stokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu_stokActionPerformed
        Rectangle pegawaiBound = this.getBounds();
        new stok(pegawaiBound, id_admin).setVisible(true);
        this.dispose();        
    }//GEN-LAST:event_menu_stokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pegawai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */     
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new pegawai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane alamatScrollPane;
    private utility.bg2 bg21;
    private javax.swing.JButton btn_bersihkan;
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JButton btn_ubah;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser date_tgl_lahir;
    private javax.swing.JPanel header_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton menu_barang;
    private javax.swing.JButton menu_laporan;
    private javax.swing.JButton menu_pegawai;
    private javax.swing.JButton menu_pembelian;
    private javax.swing.JButton menu_penjualan;
    private javax.swing.JButton menu_penyesuaian;
    private javax.swing.JButton menu_stok;
    private javax.swing.JButton menu_supplier;
    private javax.swing.JRadioButton rb_pria;
    private javax.swing.JRadioButton rb_wanita;
    private javax.swing.JTextArea ta_alamat;
    private javax.swing.JScrollPane tabelScrollPane;
    private javax.swing.JTable tbl_pegawai;
    private javax.swing.JTextField tf_nama;
    private javax.swing.JTextField tf_no_telp;
    private javax.swing.JTextField tf_tmpt_lahir;
    // End of variables declaration//GEN-END:variables
}
